### ISSUE TITLE
OptiX (CPU) tracking issue

### ISSUE THREAD

**Issue by RDambrosio016** [Rust-GPU/Rust-CUDA#3]
Issue to track what needs to be done to complete the CPU (host) side of OptiX:

(me) Denoising:
- [ ] optixDenoiserComputeIntensity
- [ ] optixDenoiserComputeAverageColor
- [ ] `setup_state_with_buffers`
- [ ] Some way of running the denoiser with the same input and output image.
- [ ] AOV models
- [ ] Tiled denoising

(@anderslanglands) Actual Raytracing:
- [ ] port remaining iw examples
- [ ] port SDK examples necessary to test remaining features (e.g. motion blur, curves)
- [ ] implement instance transforms, motion blur
